fs=32;
n=0:1:fs;
y=sin(2*pi*n/fs);
subplot(3,2,1);
stem(y);
ylabel('Amplituda');
xlabel('Numer probki');
title('Re(y)');
axis([-inf inf -inf inf]);
subplot(3,2,2);
stem(imag(y));
ylabel('Amplituda');
xlabel('Numer probki');
title('Im(y)');
y1=2*fft(y)/fs;
subplot(3,2,3);
stem(real(y1));
ylabel('Amplituda');
xlabel('Numer pasma czestotliwosciowego');
title('Re(fft(y))');
axis([0 33 -inf inf]);
subplot(3,2,4);
stem(imag(y1));
ylabel('Amplituda');
xlabel('Numer pasma czestotliwosciowego');
title('Im(fft(y))');
axis([0 33 -inf inf]);
subplot(3,2,5);
stem(abs(y1));
ylabel('Magnituda');
xlabel('Numer pasma czestotliwosciowego');
title('Modul(fft(y))');
axis([0 33 -inf inf]);
subplot(3,2,6);
stem(angle(y1)/pi);
ylabel('Faza [pi x rad]');
xlabel('Numer pasma czestotliwosciowego');
title('Phase(fft(y))');
axis([0 33 -inf inf]);