N=32;
n=1:1:N;
y1=cos(2*pi*n/N+pi/4);
y2=0.5*cos(4*pi*n/N);
y3=0.25*cos(8*pi*n/N+pi/2);
y4=y1+y2+y3;
y1fft=2*fft(y1)/N;
y2fft=2*fft(y2)/N;
y3fft=2*fft(y3)/N;
y4fft=2*fft(y4)/N;
figure
subplot(2,2,1);
stem(abs(y1fft));
xlabel('Numer pasma czestotliwosciowego');
ylabel('Magnituda');
title('y1[n]=cos(2\pin/N+\pi/4)');
subplot(2,2,2);
stem(abs(y2fft));
xlabel('Numer pasma czestotliwosciowego');
ylabel('Magnituda');
title('y2[n]=0.5cos(4\pin/N)');
subplot(2,2,3);
stem(abs(y3fft));
xlabel('Numer pasma czestotliwosciowego');
ylabel('Magnituda');
title('y3[n]=0.25cos(8\pin/N+\pi/2)');
subplot(2,2,4);
stem(abs(y4fft));
xlabel('Numer pasma czestotliwosciowego');
ylabel('Magnituda');
title('y4[n]=y1+y2+y3');
