N=32;
n=linspace(1,N,N);
y1=cos(2*pi*n/N+pi/4);
y2=0.5*cos(4*pi*n/N);
y3=0.25*cos(8*pi*n/N+pi/2);
y4=y1+y2+y3;
y4fft=2*fft(y4)/N;
subplot(2,2,1);
stem(y4);
xlabel('Numer probki');
ylabel('Amplituda');
title('y4=y1+y2+y3');
subplot(2,2,2);
stem(abs(y4fft));
xlabel('Numer pasma czestotliwosciowego');
ylabel('Magnituda');
title('Modul widma');
subplot(2,2,3);
stem(angle(y4fft)/pi);
xlabel('Numer pasma czestotliwosciowego');
ylabel('Faza [pi x rad]');
title('Faza Widma');
subplot(2,2,4);
stem(N/2*ifft(y4fft));
xlabel('Numer probki');
ylabel('Amplituda');
title('ifft(Y)');
