fs=32;
t=n=0:1:fs;
y=sin(2*pi*t/fs);
fou=fft(y);
ifou=ifft(fou);
fou=2*fou/fs;
subplot(3,2,1);
stem(y);
ylabel('Amplituda');
xlabel('Numer probki');
title('Re(y)');
subplot(3,2,2);
stem(imag(y));
ylabel('Amplituda');
xlabel('Numer probki');
title('Im(y)');
subplot(3,2,3);
stem(abs(fou));
ylabel('Magnituda');
xlabel('Numer pasma czestotliwosciowego');
title('Modul(fft(y))');
axis([0 35 0 inf]);
subplot(3,2,4);
stem(angle(fou)/pi);
ylabel('Faza [pi x rad]');
xlabel('Numer pasma czestotliwosciowego');
title('Faza(fft(y))');
axis([0 35 -1 1]);
subplot(3,2,5);
stem(real(ifou));
ylabel('Amplituda');
xlabel('Numer probki');
title('Re(ifft(y))');
axis([0 35 -1 1]);
subplot(3,2,6);
stem(imag(ifou));
ylabel('Amplituda');
xlabel('Numer probki');
title('Im(ifft(y))');
axis([0 35 -1 1]);
