k=1;
N=32;
n=linspace(1,N,N);
omega=2*pi*k/N;
phi=pi/2;
y=exp(1i*(omega*n+phi));
subplot(3,2,1);
stem(real(y));
xlabel('Numer probki');
ylabel('Amplituda');
title('Re(y)');
subplot(3,2,2);
stem(imag(y));
xlabel('Numer probki');
ylabel('Amplituda');
title('Im(y)');
y1=(2*fft(y)/N);
subplot(3,2,3);
stem(real(y1));
xlabel('Numer pasma czestotliwosciowego');
ylabel('Amplituda');
title('Re(fft(y))');
axis([0 35 -inf inf]);
subplot(3,2,4);
stem(imag(y1));
xlabel('Numer pasma czestotliwosciowego');
ylabel('Amplituda');
title('Im(fft(y))');
axis([0 35 -inf inf]);
subplot(3,2,5);
stem(abs(y1));
xlabel('Numer pasma czestotliwosciowego');
ylabel('Magnituda');
title('Modul(fft(y))');
axis([0 35 -inf inf]);
subplot(3,2,6);
stem(angle(y1)/pi);
xlabel('Numer pasma czestotliwosciowego');
ylabel('Faza [pi x rad]');
title('Phase(fft(y))');
axis([0 35 -inf inf]);
