fs=8000;
time=5;
alf=0.99;
t=0:1/fs:time-1/fs;
gauss = randn(1,time*fs);
fsin = 1000;
sinusoida = sin(2*pi*fsin*t);
signal = chirp(t,0,time,1000);
[voice,fn] = audioread('My Voice 8kHz.wav');

subplot(2,2,1);
spectrogram(gauss,hamming(256),[],[],fs,'yaxis');
xlabel('Time (secs)');
ylabel('Frequency (kHz)');
title('Sygna³ szumu');
subplot(2,2,2);
spectrogram(sinusoida,hamming(256),[],[],fs,'yaxis');
xlabel('Time (secs)');
ylabel('Frequency (kHz)');
title('Sygna³ sinusoidalny o sta³ej czêstotliwoœci');
subplot(2,2,3);
spectrogram(signal,hamming(256),[],[],fs,'yaxis');
xlabel('Time (secs)');
ylabel('Frequency (kHz)');
title('Sygna³ o zmiennej czêstotliwoœci');
subplot(2,2,4);
spectrogram(voice,hamming(256),[],[],fs,'yaxis');
xlabel('Time (secs)');
ylabel('Frequency (kHz)');
title('Sygna³ mowy');